// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcqD0g3mlgir7Fhqi3YfH7piEiWfiLKyI',
    appId: '1:707312703311:web:6c768ba0201bc1d64a173a',
    messagingSenderId: '707312703311',
    projectId: 'liseli-buyukelciler-db',
    authDomain: 'liseli-buyukelciler-db.firebaseapp.com',
    storageBucket: 'liseli-buyukelciler-db.firebasestorage.app',
    measurementId: 'G-BM291ETPWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaMG-INyfbM1NtSdMJLfIr_gW_w0GJMI8',
    appId: '1:707312703311:android:0fa7a526e4121ee74a173a',
    messagingSenderId: '707312703311',
    projectId: 'liseli-buyukelciler-db',
    storageBucket: 'liseli-buyukelciler-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3tkfyCcrL07qndsDqVsBf5j1ZjadAkBw',
    appId: '1:707312703311:ios:c7ae1bab651755f54a173a',
    messagingSenderId: '707312703311',
    projectId: 'liseli-buyukelciler-db',
    storageBucket: 'liseli-buyukelciler-db.firebasestorage.app',
    iosBundleId: 'com.eceyazilim.sosyalmedya',
  );
}
